simulation-settings:
  user-workflow:
    workflow-name: "fluxo-spend"
    deployment-registry: "private"
  workflow-artifacts:
    workflow-path: "./main.ts"
    config-path: "./config.simulation.json"
    secrets-path: ""
