import { useRef, useState } from 'react';
import { ArrowRight, Check, Eye, Fingerprint, ShieldCheck, Sparkles } from 'lucide-react';
import { emptyProfile, personaliseAnswer, rewriteLocally, scrub, type Profile, type PrivacyReview } from '../lib/privacy';
import { askPrivately } from '../lib/ask';
import { ApiError, explorer, type PublicConfig } from '../lib/api';
import type { CreditNote } from '../lib/notes';
import { ExternalLink } from './Primitives';

export function QuestionPanel({ config, notes, reload, locked, setLocked }: { config?: PublicConfig; notes: CreditNote[]; reload: () => void; locked: boolean; setLocked: (value: boolean) => void }) {
  const running = useRef(false);
  const [question, setQuestion] = useState(''), [profile, setProfile] = useState<Profile>(emptyProfile), [review, setReview] = useState<PrivacyReview>(), [approved, setApproved] = useState(false), [useLocalModel, setUseLocalModel] = useState(false);
  const [busy, setBusy] = useState(false), [status, setStatus] = useState(''), [error, setError] = useState(''), [answer, setAnswer] = useState<ReturnType<typeof personaliseAnswer>>(), [spendTx, setSpendTx] = useState('');
  const selected = notes.find(n => n.leafIndex !== null && n.nextI < 200);
  function resetReview() { setReview(undefined); setApproved(false); setAnswer(undefined); setError(''); setStatus(''); setSpendTx(''); }
  function updateProfile(field: keyof Profile, value: string) { setProfile(p => ({ ...p, [field]: value })); resetReview(); }
  async function run(action: () => Promise<void>) { if (running.current || locked) return; running.current = true; setBusy(true); setLocked(true); setError(''); try { await action(); } catch (e) { setError(e instanceof Error ? e.message : 'The request could not be completed.'); if (e instanceof ApiError && e.spendTx) setSpendTx(e.spendTx); } finally { running.current = false; setBusy(false); setLocked(false); reload(); } }
  async function preview() { setAnswer(undefined); setApproved(false); setStatus(useLocalModel ? 'Rewriting with Ollama on this device…' : 'Checking your question locally…'); const checked = useLocalModel ? await rewriteLocally(question, profile) : scrub(question, profile); setReview(checked); setStatus('Review the outgoing question before sending.'); }
  async function send() {
    if (!config || !selected || !review || !approved) return;
    setApproved(false); setAnswer(undefined); setSpendTx('');
    const result = await askPrivately(config, selected, review.text, setStatus, reload);
    setAnswer(personaliseAnswer(result.text, profile)); setSpendTx(result.spendTx ?? ''); setStatus('Your answer was decrypted in this browser.');
  }
  return <section className="question-panel" aria-labelledby="question-title"><div className="panel-heading"><span className="mono">01 / YOUR QUESTION</span><span className="local-badge"><Fingerprint size={13} />Stays local until you approve</span></div><h2 id="question-title">What’s on your mind?</h2><p className="panel-description">Ask freely. Then choose exactly what you share.</p>
    <div className="question-input-wrap"><label className="sr-only" htmlFor="question">Your private question</label><textarea id="question" placeholder="I’d like some advice about…" maxLength={10_000} value={question} disabled={busy || locked} onChange={e => { setQuestion(e.target.value); resetReview(); }} /><div className="question-input-footer"><button disabled={busy || locked} onClick={() => { setProfile({ name: 'Alex', age: '34', city: 'Singapore', privateTerms: 'Meridian Labs' }); setQuestion('My name is Alex, I am 34 and live in Singapore. I work at Meridian Labs. How can I build a better routine around a busy work schedule? Contact me at alex@example.com.'); resetReview(); }}>Try a sample <Sparkles size={12} /></button><span>{question.length.toLocaleString()} / 10,000</span></div></div>
    <details className="profile-details"><summary>Details to keep private<span>Optional <PlusIcon /></span></summary><p>These fields help the local rules find personal details. They are never added to the outgoing question.</p><div className="profile-grid"><label>Name<input autoComplete="off" value={profile.name} disabled={busy || locked} onChange={e => updateProfile('name',e.target.value)} placeholder="Your name" /></label><label>Age<input type="number" min="0" max="120" value={profile.age} disabled={busy || locked} onChange={e => updateProfile('age',e.target.value)} placeholder="Exact age" /></label><label>City<input autoComplete="off" value={profile.city} disabled={busy || locked} onChange={e => updateProfile('city',e.target.value)} placeholder="Your city" /></label><label>Other private details<input autoComplete="off" value={profile.privateTerms} disabled={busy || locked} onChange={e => updateProfile('privateTerms',e.target.value)} placeholder="Employer, names, values (comma-separated)" /></label></div></details>
    <div className="review-controls"><label className="checkbox-label"><input type="checkbox" checked={useLocalModel} disabled={busy || locked} onChange={e => { setUseLocalModel(e.target.checked); resetReview(); }} /><span>Rewrite with local Ollama <small>qwen3:8b · optional</small></span></label><button className="button button-dark" disabled={busy || locked || !question.trim()} onClick={() => run(preview)}><Eye size={16} />Preview privacy</button></div>
    {review && <section className="privacy-review" aria-labelledby="review-title"><div className="panel-heading"><span className="mono">02 / REVIEW WHAT LEAVES</span><span className="mode-badge">{review.mode === 'rules' ? 'Rules only' : 'Local model + rules'}</span></div><h3 id="review-title">A little less personal.</h3><div className="diff-grid"><div><span className="diff-label">ONLY ON YOUR DEVICE</span><p>{question}</p></div><div><span className="diff-label"><ShieldCheck size={12} />SENT AFTER YOUR APPROVAL</span><p>{review.text}</p></div></div><div className="redaction-tags">{review.removed.length ? review.removed.map(label => <span key={label}><Check size={12} />{label} removed</span>) : <span>No known personal values detected</span>}</div>
    <p className="helper-text">{review.mode === 'rules' ? 'Rules-only mode does not hide writing style. ' : ''}Scrubbing can miss details. {review.flagged.length > 0 && `Review these possible identifiers: ${review.flagged.join(', ')}.`}</p><label className="checkbox-label approval-check"><input type="checkbox" checked={approved} disabled={busy || locked} onChange={e => setApproved(e.target.checked)} /><span>I have reviewed the outgoing text, including any remaining identifiers, and approve sharing it with the model.</span></label><div className="send-row"><button className="button button-dark" disabled={busy || locked || !approved || !selected || !config?.ready.spend || !review.text.trim()} onClick={() => run(send)}>Ask privately<ArrowRight size={16} /></button><span>{!config?.ready.spend ? 'The gateway must be ready to send.' : !selected ? 'Add credits to send your question.' : 'Uses 1 credit · encrypted before sending'}</span></div></section>}
    {busy && <div className="progress-line" aria-hidden="true" />}{status && <p role="status" className="status-message">{status}</p>}{error && <p role="alert" className="error-message">{error}</p>}
    {answer && <section className="answer-panel" aria-labelledby="answer-title"><div className="panel-heading"><span className="mono">03 / JUST FOR YOU</span><ShieldCheck size={17} /></div><h3 id="answer-title">Your answer.</h3><p className="answer-copy">{answer.general}</p>{answer.advice.length > 0 && <div className="personalised-advice"><h4>Applied locally to your profile</h4>{answer.advice.map((text,i) => <p key={i}>{text}</p>)}</div>}{answer.caveats && <p className="answer-caveats">{answer.caveats}</p>}{!answer.formatted && <p className="helper-text">The model returned plain text. No local personalisation was applied.</p>}</section>}
    {spendTx && <ExternalLink href={explorer(spendTx)}>View verified credit spend</ExternalLink>}
  </section>;
}
function PlusIcon() { return <svg width="12" height="12" viewBox="0 0 12 12" aria-hidden="true"><path d="M6 1v10M1 6h10" stroke="currentColor" /></svg>; }
