# ==========================================================================
# CRE WORKFLOW SETTINGS FILE — brizo-spend
# ==========================================================================
simulation-settings:
  user-workflow:
    workflow-name: "brizo-spend"
    deployment-registry: "private"
  workflow-artifacts:
    workflow-path: "./main.ts"
    config-path: "./config.simulation.json"
    secrets-path: ""
