[toolchain]
anchor_version = "0.31.0"
package_manager = "npm"

[features]
resolution = false
skip-lint = false

[programs.devnet]
brizo_pool = "HU1m8PzF8icY7FF1psP3VLDmxm9JZbCpAkByLxF3jpYC"

[programs.localnet]
brizo_pool = "HU1m8PzF8icY7FF1psP3VLDmxm9JZbCpAkByLxF3jpYC"
test_forwarder = "5Kan8BhBcuZfGy6qhXcbta8vJ6C6YQHyqfDkMv58zGxo"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "NODE_OPTIONS=--no-experimental-strip-types npx ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
